spring:
  application:
    name: api-gateway
  datasource:
    url: jdbc:mysql://localhost:3306/cufflinks
    username: root
    password: Ashwani@1
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
      routes:
        - id: user-management-service
          uri: lb://user-management-service/
          predicates:
            - Path=/user-management-service/**
          filters:
            - RewritePath=/user-management-service/(?<path>.*), /$\{path}
            - name: CircuitBreaker
              args:
                name: mycircuitbreaker
                fallbackUri: forward:/fallback
server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    homePageUrl: https://${eureka.hostname}/

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
